# Generated by Django 3.2.9 on 2021-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новини', 'verbose_name_plural': 'Новину'},
        ),
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опублікована'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at_comments',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата коментаря'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опоблікування новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published_comments',
            field=models.BooleanField(default=True, verbose_name='Опоблікування коментраря'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Оновлення'),
        ),
    ]
