# Generated by Django 3.2.9 on 2021-11-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211129_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('news_id', models.IntegerField()),
                ('comments', models.TextField(blank=True, verbose_name='Коментарь')),
                ('created_at_comments', models.DateTimeField(auto_now_add=True, verbose_name='Дата коментаря')),
                ('is_published_comments', models.BooleanField(default=True, verbose_name='Опоблікування коментаря')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарів',
                'ordering': ['-created_at_comments'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='comments_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.comments'),
        ),
    ]
